name: Deploy WLG site to dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
            folder: ${{ github.workspace }}
            bucket: ${{ secrets.DEV_AWS_S3_BUCKET }}
            dist-id: ${{ secrets.DEV_AWS_CLOUDFRONT_DISTRIBUTION_ID }}